version: '3.8'

services:
  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mall-pos-backend
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3001}
      - DB_PATH=${DB_PATH:-/app/data/pos.db}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    volumes:
      # Persist database and uploads
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./images:/app/images
    networks:
      - mall-pos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:3001}
    container_name: mall-pos-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - backend
    networks:
      - mall-pos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  mall-pos-network:
    driver: bridge

volumes:
  # Named volumes for data persistence
  mall_pos_data:
    driver: local