version: '3.8'

services:
  # Backend Service (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: mall-pos-backend-dev
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - PORT=${PORT:-3001}
      - DB_PATH=${DB_PATH:-/app/data/pos.db}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    volumes:
      # Mount source code for hot reload
      - ./backend:/app
      - /app/node_modules
      # Persist data
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./images:/app/images
    networks:
      - mall-pos-network
    restart: unless-stopped
    command: npm run dev

  # Frontend Service - Development Mode
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:3001}
    container_name: mall-pos-frontend-dev
    env_file:
      - ./frontend/.env
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3001}
    ports:
       - "${FRONTEND_DEV_PORT:-5173}:5173"
    volumes:
      # Mount source code for hot reload
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - mall-pos-network
    restart: unless-stopped
    command: npm run dev

networks:
  mall-pos-network:
    driver: bridge