name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT || 22 }}
        script: |
          echo "Starting deployment..."
          
          # Navigate to project directory
          cd /home/deploy/mall-pos || { echo "Project directory not found!"; exit 1; }
          
          # Pull latest changes
          echo "Pulling latest changes from GitHub..."
          git pull origin main
          
          # Install backend dependencies
          echo "Installing backend dependencies..."
          cd backend
          npm install --production --silent
          
          # Build frontend
          echo "Building frontend..."
          cd ../frontend
          npm install --silent
          npm run build
          
          # Ensure production environment files are in place
          echo "Checking environment configuration..."
          if [ ! -f backend/.env ]; then
            echo "Warning: backend/.env not found, using .env.example"
            cp backend/.env.example backend/.env
          fi
          if [ ! -f frontend/.env ]; then
            echo "Warning: frontend/.env not found, using .env.example"
            cp frontend/.env.example frontend/.env
          fi
          
          # Restart backend service
          echo "Restarting backend service..."
          cd ..
          pm2 restart mall-pos-backend || pm2 start ecosystem.config.js
          
          # Update Nginx configuration if HTTPS config exists
          echo "Updating Nginx configuration..."
          if [ -f frontend/nginx-https.conf ] && [ -f /etc/letsencrypt/live/bharatkitchenware.store/fullchain.pem ]; then
            sudo cp frontend/nginx-https.conf /etc/nginx/sites-available/mall-pos
            echo "Using HTTPS configuration"
          else
            echo "SSL certificates not found, using HTTP configuration"
          fi
          
          # Test and reload nginx
          echo "Testing and reloading nginx..."
          sudo nginx -t && sudo systemctl reload nginx
          
          # Check service status
          echo "Checking service status..."
          pm2 status
          
          echo "Deployment completed successfully!"
          
    - name: Notify deployment status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Deployment successful!"
        else
          echo "❌ Deployment failed!"
        fi